### ISSUE TITLE
add metaverse community link

### ISSUE THREAD

**Issue by kquirapas** [Web3Philippines/bio#1]
Add this link: https://app.gather.town/app/EgdJnVXXhokxeu8g/web3philippines

@warengonzaga

**Comment by warengonzaga** [comment]
Right, this is a good addition.

**Comment by warengonzaga** [comment]
I am adding, the LinkedIn link as well.

**Comment by warengonzaga** [comment]
Pushed [1408069](https://github.com/web3phl/homepage/commit/1408069f4cf10a14e6f42120daef910e155f3cb9) 👀
