### ISSUE TITLE
add link category

### ISSUE THREAD

**Issue by warengonzaga** [Web3Philippines/bio#2]
It's good to have a section separator on the homepage.

**Comment by rgvillanueva28** [comment]
Can you expound this one Sir Warren?

**Comment by warengonzaga** [comment]
> Can you expound this one Sir Warren?

Check this one as example: bio.link/warengonzaga
Where you can categorize the links.

**Comment by rgvillanueva28** [comment]
What are the possible sections and where do the links belong to in a section?

Here is my idea:
### Community
- FB Group
- Discord
- Reddit
- Telegram
- Gather
- Nas.io (or in a new category: Partners?)

### Socials (and Contacts?)
- FB Page
- TikTok
- YouTube
- Instagram
- Twitter
- LinkedIn
- Email

### Sites? (Not sure on this title)
- Directory

**Comment by warengonzaga** [comment]
> What are the possible sections and where do the links belong to in a section?
> 
> Here is my idea:
> 
> ### Community
> * FB Group
> * Discord
> * Reddit
> * Telegram
> * Gather
> * Nas.io (or in a new category: Partners?)
> 
> ### Socials (and Contacts?)
> * FB Page
> * TikTok
> * YouTube
> * Instagram
> * Twitter
> * LinkedIn
> * Email
> 
> ### Sites? (Not sure on this title)
> * Directory

These are good, for the last section call it "Projects" and you're good to go.

**Comment by warengonzaga** [comment]
Merged to #11
